apriori_base/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.decorators import login_required

# My Urls

urlpatterns = [
    url(r'^$', login_required(views.index), name='index'),
    url(r'^index$', login_required(views.index), name='index'),

]

apriori_review/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required
from . import views

app_name = 'apriori_review'

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^index$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^content$', login_required(views.ContentView.as_view()), name='content'),
]

apriori_user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'apriori_user'

urlpatterns = [
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', login_required(views.LogoutView.as_view()), name='logout'),
]

apriori_web_tools/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

# My Urls
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)/$', serve, {"document_root": settings.MEDIA_ROOT}),

    url(r'', include('apriori_base.urls')),
    url(r'^user/', include('apriori_user.urls')),

    url(r'^review/', include('apriori_review.urls')),

]

apriori_review/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class AprioriReview(models.Model):
    content = models.CharField('content',max_length=520)
    create_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = 'Apriori_Review'
        verbose_name_plural = 'Apriori_Review'

apriori_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

class AprioriUser(AbstractUser):
    placeholder = models.SmallIntegerField('placeholder', default=1)
    #pl2 = models.CharField(max_length=128, default='pl2')


    class Meta:
        verbose_name = 'Apriori_User'
        verbose_name_plural = 'Apriori_User'

apriori_user/forms.py
from django import forms

from .models import AprioriUser


class LoginForm(forms.ModelForm):
    secure_code = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = AprioriUser

        fields = ['secure_code', 'username', 'password']

apriori_base/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'apriori_base/index.html')

apriori_review/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from django.views.generic import View

from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer

import datetime
from itertools import chain

from .models import AprioriReview

from .serializers import AprioriReviewSerializer

# Create your views here.


class IndexView(View):
    def get(self, request):
        template_name = 'apriori_review/index.html'
        return render(request, template_name)

class ContentView(APIView):

    def get(self, request):
        day_list = [5, 9, 15, 30, 60]

        content = AprioriReview.objects.filter(
            create_date = datetime.date.today() -
            datetime.timedelta(days=2))

        for day in day_list:
            content = chain(content ,AprioriReview.objects.filter(
                create_date = (datetime.datetime.now() -
                datetime.timedelta(days=day))))

        serializer = AprioriReviewSerializer(content, many=True)

        return Response(serializer.data)


    def post(self, request):
        new_content = request.POST.get('content')
        new_review = AprioriReview(content=new_content)
        if new_content is None:
            return HttpResponse("0")
        new_review.save()

        return HttpResponse("1")

apriori_user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic import View
from .forms import LoginForm
from django import forms

from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer

from apriori_user.models import AprioriUser
from .serializers import AprioriUserSerializer


# Create your views here.


class LoginView(View):
    form_class = LoginForm
    template_name = 'apriori_user/login.html'

    # display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        login_errors = "Sorry, something wrong!"

        # cleaned (normalized) data
        secure_code = request.POST.get('secure_code')
        username = request.POST.get('username')
        password = request.POST.get('password')

        # returns User object if credentials are correct
        if secure_code != 'a':
            return render(request, self.template_name,{'form':form,
            'login_errors':login_errors})

        # returns User object if credentials are correct
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')

        return render(request, self.template_name,{'form':form,
        'login_errors':login_errors})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/')

apriori_base/templates/apriori_base/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block apriori_title %}Web Tools{% endblock %}</title>

</head>

<body>
<header class="navbar navbar-fixed-top" id="apriori-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- item -->
        <nav class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a  href="{% url 'index' %}">&nbsp;HOME</a>
                </li>

                <li>
                    <a  href="{% url 'apriori_review:index' %}">&nbsp;REVIEW</a>
                </li>

            {% if user.is_authenticated %}
                <li><a  href="{% url 'apriori_user:logout' %}">LOGOUT</a></li>
            {% endif %}
            </ul>

        </nav>
    </div>
</header>


<div id="mainContentDiv">
    {% block apriori_body %}
        <p>Web Tools</p>
    {% endblock %}
</div>



    {% load staticfiles %}
    <script type="text/javascript" src="{% static '/js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>

    <link type="text/css" rel="stylesheet" href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static '/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <script type="text/javascript" src="{% static '/js/base.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static '/css/base.css' %}">

    {% block apriori_staticfiles %}
    {% endblock %}

</body>
</html>

apriori_base/templates/apriori_base/form-template.html
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static '/css/form-template.css' %}">


{% if sfm_errors %}
    <p style="color:red;"><strong>{{ sfm_errors }}</strong></p>
{% endif %}

{% for field in form %}
    <div class="form-group">
        <label class="form-template-field-label">{{ field.label_tag }}</label>
        <div class="form-template-field">{{ field }}</div>
    </div>
{% endfor %}

apriori_base/templates/apriori_base/index.html
{% extends 'apriori_base/base.html' %}

{% block apriori_title %}REVIEW{% endblock %}

{% block apriori_staticfiles %}
{% load staticfiles %}
    <script src="{% static '/apriori_review/js/index.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static '/apriori_review/css/index.css' %}" />
{% endblock %}


{% block apriori_body %}
INDEX HERE
{% endblock %}

apriori_review/templates/apriori_review/index.html
{% extends 'apriori_base/base.html' %}

{% block apriori_title %}REVIEW{% endblock %}

{% block apriori_staticfiles %}
{% load staticfiles %}
    <script src="{% static '/apriori_review/js/index.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static '/apriori_review/css/index.css' %}" />
{% endblock %}


{% block apriori_body %}

<div class="col-sm-12">
    <div>
        <form role="form" class="form-horizontal col-sm-12" action="" method="post">
        {% csrf_token %}

            <div id="put-data-div" class="input-group row">
                <input id="data-input" type="text" class="form-control"></input>
                <span class="input-group-btn">
                    <button id="put-data-submit" type="button" class="btn btn-default
                        col-sm-12">Put Data</button>
                </span>
            </div>
        </form>
    </div>

    <div id="put-data-status">
        <label id="put-data-status-label" >TODY</label>
    </div>


    <div id="review-content-div">
        <ul id="review-content-ul" class="list-group"></ul>
    <div>



</div>

{% endblock %}

apriori_user/templates/apriori_user/login.html
{% load staticfiles %}
<script type="text/javascript" src="{% static '/js/jquery-3.2.0.min.js' %}"></script>
<script type="text/javascript" src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>

<link type="text/css" rel="stylesheet" href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}">
<link type="text/css" rel="stylesheet" href="{% static '/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<script type="text/javascript" src="{% static '/apriori_user/js/login.js' %}"></script>
<link type="text/css" rel="stylesheet" href="{% static '/apriori_user/css/login.css' %}">



<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="login-page">
      <div class="form">
        {% include 'apriori_base/form-template.html' %}
        <button type="submit">Login</button>
      </div>
    </div>
</form>